# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-04 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='akun',
            name='alamat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='akun',
            name='no_telp',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='akun',
            name='website',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
