# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-30 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akses', '0002_auto_20160829_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akun',
            name='alamat',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='akun',
            name='no_telp',
            field=models.CharField(max_length=50),
        ),
    ]
