# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-25 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tatausaha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalKuliah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
                ('mulai_kuliah', models.DateField()),
                ('akhir_kuliah', models.DateField()),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tatausaha.Dosen')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tatausaha.Ruangan')),
            ],
        ),
        migrations.CreateModel(
            name='KontrakKuliah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=200)),
                ('mulai_kontrak', models.DateField()),
                ('akhir_kontrak', models.DateField()),
                ('nilai_akhir', models.CharField(max_length=2)),
                ('jadwal_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kuliah.JadwalKuliah')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tatausaha.Mahasiswa')),
            ],
        ),
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NilaiKuliah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.FloatField(default=0.0)),
                ('jenis', models.CharField(max_length=100)),
                ('kontrak_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kuliah.KontrakKuliah')),
            ],
        ),
    ]
