# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-04 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuliah', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nilaikuliah',
            name='kontrak_kuliah',
        ),
        migrations.RemoveField(
            model_name='kontrakkuliah',
            name='akhir_kontrak',
        ),
        migrations.RemoveField(
            model_name='kontrakkuliah',
            name='mulai_kontrak',
        ),
        migrations.AddField(
            model_name='jadwalkuliah',
            name='akhir_kontrak',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='jadwalkuliah',
            name='mata_kuliah',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='kuliah.MataKuliah'),
        ),
        migrations.AddField(
            model_name='jadwalkuliah',
            name='mulai_kontrak',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='jadwalkuliah',
            name='tahun',
            field=models.IntegerField(blank=True, default=2000),
        ),
        migrations.AddField(
            model_name='kontrakkuliah',
            name='tanggal_kontrak',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='jadwalkuliah',
            name='akhir_kuliah',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='jadwalkuliah',
            name='mulai_kuliah',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='kontrakkuliah',
            name='semester',
            field=models.CharField(choices=[('semester_1', 'Semester 1'), ('semester_2', 'Semester 2'), ('semester_3', 'Semester 3'), ('semester_4', 'Semester 4'), ('semester_5', 'Semester 5'), ('semester_6', 'Semester 6'), ('semester_7', 'Semester 7'), ('semester_8', 'Semester 8'), ('semester_9', 'Semester 9'), ('semester_10', 'Semester 10'), ('semester_11', 'Semester 11'), ('semester_12', 'Semester 12'), ('semester_pendek', 'Semester Pendek')], default='semester_1', max_length=50),
        ),
        migrations.DeleteModel(
            name='NilaiKuliah',
        ),
    ]
