# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-25 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuliah', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nilaikuliah',
            name='kontrak_kuliah',
        ),
        migrations.DeleteModel(
            name='NilaiKuliah',
        ),
    ]
