# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-25 04:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kuliah', '0002_auto_20160825_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kontrakkuliah',
            name='akhir_kontrak',
        ),
        migrations.RemoveField(
            model_name='kontrakkuliah',
            name='mulai_kontrak',
        ),
        migrations.RemoveField(
            model_name='kontrakkuliah',
            name='semester',
        ),
        migrations.AddField(
            model_name='jadwalkuliah',
            name='akhir_kontrak',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 8, 25, 4, 53, 55, 831453, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jadwalkuliah',
            name='mulai_kontrak',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 8, 25, 4, 54, 0, 73317, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jadwalkuliah',
            name='semester',
            field=models.CharField(default=datetime.datetime(2016, 8, 25, 4, 54, 3, 621581, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jadwalkuliah',
            name='akhir_kuliah',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='jadwalkuliah',
            name='mulai_kuliah',
            field=models.TimeField(blank=True),
        ),
    ]
